#!/bin/bash
#SBATCH -N 1
#SBATCH -C knl
#SBATCH -q debug
#SBATCH -J cs267
#SBATCH -t 00:30:00
#SBATCH --output=openmpv2-36-core-%j.out

#OpenMP settings:
export OMP_NUM_THREADS=36
export OMP_PLACES=cores
export OMP_PROC_BIND=spread

./openmp_crawler_v2 https://www.cplusplus.com/ ../pages_36/1/ 1
./openmp_crawler_v2 https://www.cplusplus.com/ ../pages_36/2/ 2
./openmp_crawler_v2 https://www.cplusplus.com/ ../pages_36/3/ 3
./openmp_crawler_v2 https://www.cplusplus.com/ ../pages_36/4/ 4