#!/bin/bash
#SBATCH -N 1
#SBATCH -C knl
#SBATCH -q debug
#SBATCH -J cs267
#SBATCH -t 00:30:00
#SBATCH --output=openmp-36-core-%j.out

#OpenMP settings:
export OMP_NUM_THREADS=36
export OMP_PLACES=cores
export OMP_PROC_BIND=spread


./openmp_indexer ../pages_68/1/ ../index_files/36/1_depth.txt
./openmp_indexer ../pages_68/2/ ../index_files/36/2_depth.txt
./openmp_indexer ../pages_68/3/ ../index_files/36/3_depth.txt
./openmp_indexer ../pages_68/4/ ../index_files/36/4_depth.txt